package com.landrop.receiver.protocol

// These names are the explicit, case-sensitive JSON enum values.
enum class PresentationMode { GUI, NOTIFICATION }
enum class Decision { ACCEPT, REJECT }
enum class DeliveryState {
    DISCOVERING, AVAILABLE, CONNECTING, SECURE_CHANNEL, SESSION_ESTABLISHED,
    REQUEST_SENT, WAITING_FOR_DECISION, ACCEPTED, TRANSFER_PREPARING, TRANSFERRING,
    VERIFYING, VERIFIED, INSTALL_READY, INSTALLATION_HANDOFF, COMPLETED,
    REJECTED, FAILED, CANCELLED,
}
enum class ErrorCode {
    INVALID_REQUEST, UNSUPPORTED_PROTOCOL, REQUEST_EXPIRED, USER_REJECTED,
    TRANSFER_CANCELLED, TRANSFER_TIMEOUT, CONNECTION_LOST, FILE_TOO_LARGE,
    INVALID_METADATA, INTEGRITY_MISMATCH, INSTALLATION_UNAVAILABLE, INTERNAL_ERROR,
}
